name: insurance_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  responsive_builder: 0.3.0
  device_info: ^1.0.0
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: DM Serif Display
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf
    - family: Karla
      fonts:
        - asset: fonts/Karla-Medium.ttf

